// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "routetracker-20181211084302-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://routetracker-20181211084302-hostingbucket.s3-website-us-east-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "us-east-1:447a210b-3b02-4fff-994f-ff2e3b81a78d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_JSPJJUX9v",
    "aws_user_pools_web_client_id": "15bln0n6tj8etn8q527fdn7gpo",
    "aws_appsync_graphqlEndpoint": "https://arppc2xe35c4zhfmpcnakjkbce.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
